### PR TITLE
changed success screen continue button label to finish

### LINKED ISSUE #422: Account creation success screen, the button label is wordy.
## Describe the bug / expected behavior

The "press continue to finish" is wordy... I know on docit we have "press finish to continue", but now that I look at it, this line is completely unnecessary.

## Screenshots / Screen recording

image

## Anything else to add?
Ensure it reads properly in other languages too.

### PR DESCRIPTION
**Pull request by RaghavendranC-Eaton**
Fixes #422 

#### Changes proposed in this Pull Request:

-
-
-

#### Screenshots / Screen Recording (if applicable)

- 
Screenshot 2023-08-22 at 2 28 19 PM

#### To Test:

- yarn start:example

#### Any specific feedback you are looking for?

- changed the "Press finish to continue" in all translations

### CODE REVIEW

**Review by daileytj — APPROVED** [review]

**Review by daileytj — APPROVED** [review]

**Comment by huayunh** [comment]
Why is that "press finish to continue" line present in your screenshot?

File: login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/english.ts [hunk 1]
```diff
@@ -21,9 +21,9 @@ const resources: RegistrationLanguageFile = {
...
             },
             SUCCESS_MESSAGE:
-                'Your account has been successfully created with the email <b>{{email}}</b>.\n\nYour account has already been added to the <b>{{organization}}</b> organization.\n\nPress continue below to finish.',
+                'Your account has been successfully created with the email <b>{{email}}</b>.\n\nYour account has already been added to the <b>{{organization}}</b> organization.',
             SUCCESS_MESSAGE_ALT:
-                'Your account has been successfully created with the email <1>{{email}}</1>.\n\nYour account has already been added to the <3>{{organization}}</3> organization.\n\nPress continue below to finish.',
+                'Your account has been successfully created with the email <1>{{email}}</1>.\n\nYour account has already been added to the <3>{{organization}}</3> organization.',
             SUCCESS_EXISTING:
                 'Your account has been successfully created. Please log in with your Eaton account email and password.',
             FAILURE_MESSAGE: 'We were unable to complete your registration. Press continue below to finish.',
```
Comment (huayunh) [inline login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/english.ts:29]: what about this line?
